import React from "react";
import PlayerLevelSelector from "../Components/PlayerLevelSelector";
import ChallengeAndSize from "../Components/ChallengeAndSize";
import "../CSS/FinderStyles.css";
import AlignmentTypeSelector from "../Components/AlignmentTypeSelector";
import MonsterTypeSelector from "../Components/MonsterTypeSelector";
import { Link } from "react-router-dom";

class EncounterBuilder extends React.Component {
  render() {
    return (
      <React.Fragment>
        <h4 id="promptHeader">
          Enter your party information and encounter preferences
        </h4>

        <article class="mainArticle" id="filter-body">
          {/* <!-- css style for the whole page frame --> */}
          <div class="parent-container-list-vertical">
            {/* <!-- FIRST PAIRING --> */}
            <div class="parent-container-pair-horizontal">
              {/* <!-- css style for the first two items --> */}

              {/* <!-- ITEM 1 IN FIRST PAIRING -->
            <!--CHALLENGE RATING SELECTOR--> <!-- first item in sub pairing --> */}
              <PlayerLevelSelector />

              {/* <!-- ITEM 2 IN FIRST PAIRING -->
            <!-- SUB PAIRING IN 2ND ITEM OF FIRST PAIRING --> */}
              <div class="sub-container-pair-horizontal">
                <div class="sub-container-pair-vertical">
                  {/* <!-- these parameters should be in a list -->
                    <!--CHALLENGE RATING SELECTOR--> <!-- first item in sub pairing --> */}

                  <ChallengeAndSize />
                  <AlignmentTypeSelector />
                  <MonsterTypeSelector />

                  {/* <!-- second item in inner horizontal pairing --> */}
                  {/* <fieldset fieldset class="checkbox" id="movementSelector">
                    <legend>Movement</legend>
                    <ul class="movementCheckbox">
                      <li>
                        <input
                          id="walk"
                          type="checkbox"
                          name="movement"
                          value="walk"
                        >
                          <label for="walk">Walk</label>
                        </input>
                      </li>
                      <li>
                        <input
                          id="fly"
                          type="checkbox"
                          name="movement"
                          value="fly"
                        >
                          <label for="fly">Fly</label>
                        </input>
                      </li>
                      <li>
                        <input
                          id="swim"
                          type="checkbox"
                          name="movement"
                          value="swim"
                        >
                          <label for="swim">Swim</label>
                        </input>
                      </li>
                      <li>
                        <input
                          id="climb"
                          type="checkbox"
                          name="movement"
                          value="climb"
                        >
                          <label for="climb">Climb</label>
                        </input>
                      </li>
                      <li>
                        <input
                          id="burrow"
                          type="checkbox"
                          name="movement"
                          value="burrow"
                        >
                          <label for="burrow">Burrow</label>
                        </input>
                      </li>
                    </ul>
                  </fieldset> */}
                </div>
                {/* <!-- end inner horizontal poairing --> */}
              </div>
              {/* <!-- end first pairing --> */}

              {/* <!-- SECOND PAIRING -->
        <!-- JENA'S .TS GENERATED FIELDS --> */}
              <div class="parent-container-pair-horizontal">
                <div class="filter-component" id="alignmentSelector"></div>
                <div class="filter-component" id="typeSelector"></div>
                {/* <!-- this is the type selector field. it is generated by typescript -->  */}
              </div>
              {/* <!--end second pairing--> */}

              {/* <!-- THIRD PAIRING --> */}
              <div
                class="parent-container-pair-horizontal"
                id="resultsButtonContainer"
              >
                <Link to="/encounterResults">
                  <button
                    className="button"
                    onClick="window.location.href = '/encounterResults;"
                    title="Encounter Results"
                  >
                    Build Encounter
                  </button>
                </Link>
              </div>
              {/* <!-- end third pairing --> */}
            </div>
          </div>
        </article>
      </React.Fragment>
    );
  }
}

export default EncounterBuilder;
