import React from "react";
import ChallengeAndSize from "../Components/ChallengeAndSize";
import "../CSS/FinderStyles.css";
import { Link } from "react-router-dom";
import MonsterTypeSelector from "../Components/MonsterTypeSelector";
import AlignmentTypeSelector from "../Components/AlignmentTypeSelector";
import Movement from "../Components/Movement";

class MonsterFinder extends React.Component {
  render() {
    return (
      <React.Fragment>
        <h4 id="promptHeader">
          Enter your party information and encounter preferences
        </h4>

        <article class="mainArticle" id="filter-body">
          {/* <!-- css style for the whole page frame --> */}
          <div class="parent-container-list-vertical">
            {/* <!-- FIRST PAIRING --> */}
            <div class="parent-container-pair-horizontal">
              {/* <!-- css style for the first two items --> */}

              {/* <!-- ITEM 1 IN FIRST PAIRING -->
            <!--CHALLENGE RATING SELECTOR--> <!-- first item in sub pairing --> */}

              {/* <!-- ITEM 2 IN FIRST PAIRING -->
            <!-- SUB PAIRING IN 2ND ITEM OF FIRST PAIRING --> */}
              <div class="sub-container-pair-horizontal">
                <div class="sub-container-pair-vertical">
                  {/* <!-- these parameters should be in a list -->
                    <!--CHALLENGE RATING SELECTOR--> <!-- first item in sub pairing --> */}

                  <ChallengeAndSize />
                  <AlignmentTypeSelector />
                  <MonsterTypeSelector />

                  {/* <!-- second item in inner horizontal pairing --> */}
                  <fieldset fieldset class="checkbox" id="movementSelector">
                    <legend>Movement</legend>
                    <Movement />
                  </fieldset>
                </div>
                {/* <!-- end inner horizontal poairing --> */}
              </div>
              {/* <!-- end first pairing --> */}

              {/* <!-- SECOND PAIRING -->
        <!-- JENA'S .TS GENERATED FIELDS --> */}
              <div class="parent-container-pair-horizontal">
                <div class="filter-component" id="alignmentSelector"></div>
                <div class="filter-component" id="typeSelector"></div>
                {/* <!-- this is the type selector field. it is generated by typescript -->  */}
              </div>
              {/* <!--end second pairing--> */}

              {/* <!-- THIRD PAIRING --> */}
              <div
                class="parent-container-pair-horizontal"
                id="resultsButtonContainer"
              >
                <Link to="/encounterBuilder">
                  <button
                    className="button"
                    onClick="window.location.href = '/monsterResults';"
                    title="Monster Results"
                  >
                    Find Monsters
                  </button>
                </Link>
              </div>
              {/* <!-- end third pairing --> */}
            </div>
          </div>
        </article>
      </React.Fragment>
    );
  }
}
export default MonsterFinder;
